imports:
    {ressource: parameters.yaml}

parameters:
    env(DATABASE_URL): "mysql://%symfony_database_user%:%symfony_database_password%@%symfony_database_host%:%symfony_database_port%/%symfony_database_name%"
    # "mysql://root:@127.0.0.1:3306/hanoverfaq?serverVersion=8&charset=utf8mb4"
    env(DATABASE_MANTIS_URL) : "mysql://%mantis_database_user%:%mantis_database_password%@%mantis_database_host%:%mantis_database_port%/%mantis_database_name%"

doctrine:
    dbal:
        default_connection: symfony_connection
        connections:
            symfony_connection:
                charset: utf8
                url: '%env(resolve:DATABASE_URL)%'
                host: '%symfony_database_host%'
                port: '%symfony_database_port%'
                user: '%symfony_database_user%'
                password: '%symfony_database_password%'
                dbname: '%symfony_database_name%'
            mantis_connection:
                charset: utf8
                url: '%env(resolve:DATABASE_MANTIS_URL)%'
                host: '%mantis_database_host%'
                port: '%mantis_database_port%'
                user: '%mantis_database_user%'
                password: '%mantis_database_password%'
                dbname: '%mantis_database_name%'
            

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
